- API.md
for the `no-trash` option of `data-objects?op=remove`... perhaps...  consider `use-trash` with `default: 1` instead?
> suggested changes

- CMakeLists.txt
- README.md
- src/common.cpp
- src/common.hpp
- src/endpoints/authentication/CMakeLists.txt
- src/endpoints/authentication/impl.cpp
- src/globals.cpp
- src/globals.hpp
- src/main.cpp
- test/test_auth_endpoint.py
Implemented a new OIDC flow. Rebased onto main and resolved several issues of rebasing thereafter.
> Implement Authorization Code grant OIDC flow

- src/endpoints/authentication/impl.cpp
- src/main.cpp
Generate & check OAuth state value.
> [#121] Implement OAuth state parameter

- API.md
- src/endpoints/data_objects/impl.cpp
- test/test_irods_http_api.py
> [#113] Add support for modifying replica properties

- API.md
> [_140] Add OIDC authentication documentation

- API.md
- endpoints/collections/src/main.cpp
- test/test_irods_http_api.py
All tests pass.
No OIDC tests were run for this.
> [#166] Implement set_inheritance operation for /collections endpoint

- core/include/irods/private/http_api/common.hpp
- core/src/common.cpp
- endpoints/authentication/src/main.cpp
- endpoints/collections/src/main.cpp
- endpoints/data_objects/src/main.cpp
- endpoints/information/src/main.cpp
- endpoints/query/src/main.cpp
- endpoints/resources/src/main.cpp
- endpoints/rules/src/main.cpp
- endpoints/tickets/src/main.cpp
- endpoints/users_groups/src/main.cpp
- endpoints/zones/src/main.cpp
- test/test_irods_http_api.py
> Use generic dispatch mechanism to execute endpoint operations

- test/test_irods_http_api.py
> [#220] Adjust tests for registration and copy operations

- endpoints/collections/src/main.cpp
- endpoints/data_objects/src/main.cpp
- test/test_irods_http_api.py
> Return HTTP 200 when inputs to stat operation are valid

- README.md
- core/src/main.cpp
- endpoints/authentication/src/main.cpp
Provides a configurable claim name for the mapping of OIDC users to iRODS users.
> [_163] Allow custom irods username claim

- API.md
- endpoints/information/src/main.cpp
- test/test_irods_http_api.py
All tests pass (including OIDC tests).
> [#224] Skip Basic authentication test if OIDC is enabled

- README.md
table of contents now renders more as expected
> [43] update README.md indentation

- CMakeLists.txt
- core/CMakeLists.txt
- endpoints/authentication/CMakeLists.txt
- endpoints/collections/CMakeLists.txt
- endpoints/data_objects/CMakeLists.txt
- endpoints/information/CMakeLists.txt
- endpoints/query/CMakeLists.txt
- endpoints/resources/CMakeLists.txt
- endpoints/rules/CMakeLists.txt
- endpoints/shared/CMakeLists.txt
- endpoints/tickets/CMakeLists.txt
- endpoints/users_groups/CMakeLists.txt
- endpoints/zones/CMakeLists.txt
> [#258] Restore build compatibility with iRODS 4.3.1 packages (4-3-stable)

- CMakeLists.txt
- core/CMakeLists.txt
In service of irods/irods#7220
Merge irods/irods#7526 before merging this.
> [irods/irods#7220] Do not explicitly build against libc++ (main)

- core/CMakeLists.txt
In service of irods/irods#6256
Merge irods/irods#7527 first
> [irods/irods#6256] update spdlog target (4-3-stable)

- test/test_irods_http_api.py
> [#287] Fix data object copy operation test (4-3-stable)

- endpoints/tickets/src/main.cpp
- test/test_irods_http_api.py
> [#134] Add support for setting ticket expiration (4-3-stable)

- .clang-tidy
- API.md
- endpoints/query/src/main.cpp
- test/test_irods_http_api.py
> [#276] Add support for adding/removing specific queries (4-3-stable)

- API.md
> [#294] Fix API documentation for modify_metadata/modify_permissions operations (4-3-stable)

- core/src/common.cpp
No test for this since it requires the test to control the HTTP API server.
All tests pass. This did not include testing OIDC.
> [#300] Check OIDC configuration exists during bearer token resolution (main)

- endpoints/data_objects/src/main.cpp
No tests necessary for this.
No existing tests to tweak for this.
> [#180] Remove "registered" property from stat response

- core/src/main.cpp
Here's an example:
```
$ ./irods_http_api ../irods_client_http_api/config.jso
Error: Cannot access configuration file [../irods_client_http_api/config.jso].
```
> [#337] Print clear error message when config file path is invalid

- core/src/main.cpp
Using the same scenario given in issue:
```
$ irods_http_api config.json 
Validating configuration file ...
No JSON schema file provided. Using default.
Configuration passed validation!
[2024-11-05 20:21:04.138] [P:16496] [info] [T:16496] Initializing server.
[2024-11-05 20:21:04.138] [P:16496] [trace] [T:16496] Verifying OIDC endpoint configuration
[2024-11-05 20:21:04.140] [P:16496] [error] [T:16496] Did not get a status code 200 OK response from OpenID Provider.
[2024-11-05 20:21:04.140] [P:16496] [error] [T:16496] Invalid OIDC configuration, server not starting.
```
> [#356] Check response code, ensure required OpenID metadata given

- core/src/openid.cpp
This PR is built on top of #344.
This PR performs further validation of the OAuth introspection response by using the optional response values if available.
Still needs to be tested.
> [#270] Validate OAuth Token Introspection response

- README.md
- core/include/irods/private/http_api/openid.hpp
- core/src/common.cpp
- core/src/main.cpp
- core/src/openid.cpp
- endpoints/authentication/src/main.cpp
Still need to test, add missing code, perform more error checks.
> [#107] Validate OpenID ID Tokens in client mode

- core/src/openid.cpp
Reject access tokens without aud claim
> [#375] Handle missing aud claim in access token

- endpoints/data_objects/src/main.cpp
- test/test_irods_http_api.py
Verified tests trigger the segfault.
Verified the code change resolves the segfault.
> [#402] Server does not segfault on multiple calls to parallel_write_init

- .github/workflows/build-irods-http-api-ubuntu.yml
- core/src/main.cpp
- core/src/openid.cpp
- irods_builder.Dockerfile
Addresses #411
In service of irods/irods#7726
In service of irods/irods#8330
> [#411,irods/irods#7726,irods/irods#8330] Migrate to system CMake and (partially) nlohmann-json, fix build against irods 5+

- .github/workflows/build-irods-http-api-enterprise-linux-10.yml
- .gitignore
- CMakeLists.txt
- core/CMakeLists.txt
- core/include/irods/private/http_api/common.hpp
- core/src/common.cpp
- endpoints/query/src/main.cpp
Addresses #433
In service of irods/irods#8099
In service of irods/irods#8454
In service of irods/irods#8581
In service of irods/irods#8596
The EL10 GHA workflows added by this PR will fail until packages for 5.0.2 are published.
Companion to irods/irods#8579
> [#433,irods/irods#8099,irods/irods#8454,irods/irods#8581,irods/irods#8596] Update for EL10 and Debian 13

- API.md
- endpoints/data_objects/src/main.cpp
- test/test_irods_http_api.py
> [#399] parallel_write_init: Allow targeting replicas via replica number (main)
