README.md
src/main.cpp

Verified at the bench that everything works.
Just need to figure out how to write a test for it. This may require more machinery since setting up an iRODS server is out-of-scope for this.
I also need to update the README.

[#55] Added support for TLS/SSL between HTTP API and iRODS

---

README.md
build_packages.sh
irods_builder.Dockerfile
irods_runner.Dockerfile
src/main.cpp

This includes compiling GenQuery2.
This currently compiles and runs on Ubuntu 22. ~I have to work out some issues with invoking the GenQuery2 parser before this is ready.~
I'm also still settling on the design.
Thoughts and opinions welcome.

[#114] Add Dockerfiles for building and running HTTP API (main)

---

src/CMakeLists.txt
src/common.cpp
src/common.hpp
src/endpoints/authentication/impl.cpp
src/endpoints/collections/impl.cpp
src/endpoints/data_objects/impl.cpp
src/endpoints/query/impl.cpp
src/endpoints/resources/impl.cpp
src/endpoints/rules/impl.cpp
src/endpoints/shared_api_operations.cpp
src/endpoints/tickets/impl.cpp
src/endpoints/users_groups/impl.cpp
src/endpoints/zones/impl.cpp
src/main.cpp
src/process_stash.cpp
src/process_stash.hpp

This should fix the potential `process_stash` issues stated in irods/irods#7297.
This solution just returns a copy of the object desired, rather than providing a pointer.
All existing tests pass with the changes.

`process_stash` fix

---

API.md
README.md
src/endpoints/collections/impl.cpp
src/endpoints/data_objects/impl.cpp
src/endpoints/information/impl.cpp
src/endpoints/query/impl.cpp
src/endpoints/resources/impl.cpp
src/endpoints/rules/impl.cpp
src/endpoints/shared_api_operations.cpp
src/endpoints/tickets/impl.cpp
src/endpoints/users_groups/impl.cpp
src/endpoints/zones/impl.cpp
src/main.cpp
src/session.cpp
src/session.hpp
test/test_irods_http_api.py

All tests pass.
Changing the response structure required formatting lots of code. Consider looking at each commit in isolation. The last commit is just formatting + one code comment adjustment.
Client IP addresses aren't logged yet, but this PR makes it possible to capture them. I haven't decided how to handle that. Still thinking through the design and implementation. Logging IPs is looking like a 0.2.0 thing.

More 0.1.0 changes

---

README.md

Add missing documentation on 'state_timeout_in_seconds' parameter.

[#121] Add missing OIDC documentation

---

API.md
src/common.cpp
src/common.hpp
src/endpoints/authentication/impl.cpp
test/requirements.txt

All tests pass with this change.
Also, the server is now detecting the absence of the anonymous user and reporting the appropriate error. I think the original behavior I was seeing was due to old build artifacts. Recompiling from scratch resolved the issue.

Add support for the anonymous user account and record python dependencies for testing

---

endpoints/authentication/src/main.cpp
test/test_irods_http_api.py

All tests pass _(excluding OIDC tests)_.

[#139,#165] Return 405 when HTTP GET is used for basic authentication

---

README.md
core/CMakeLists.txt
core/include/irods/private/http_api/common.hpp
core/src/common.cpp
core/src/main.cpp
endpoints/authentication/src/main.cpp

Simplify OIDC configuration by using one 'provider_url', instead of three different parameters.
Additionally, use boost url in the parsing of OIDC urls.

Update OIDC configuration, use boost url

---

README.md
core/CMakeLists.txt
core/include/irods/private/http_api/transport.hpp
core/src/main.cpp
core/src/transport.cpp
endpoints/authentication/src/main.cpp

Use TLS/SSL for OIDC communication when given an `https://...` link.

[#164] Implement TLS/SSL OIDC communication

---

core/src/common.cpp
core/src/main.cpp
endpoints/collections/src/main.cpp
endpoints/data_objects/src/main.cpp
endpoints/query/src/main.cpp
endpoints/resources/src/main.cpp
endpoints/rules/src/main.cpp
endpoints/shared/src/shared_api_operations.cpp
endpoints/tickets/src/main.cpp
endpoints/users_groups/src/main.cpp
endpoints/zones/src/main.cpp

In service of irods/irods#7220
In libstdc++, `log` is defined as a math function, so `namespace log = irods:http:log` causes errors when building.
This PR changes all instances of `namespace log` to `namespace logging`.

[irods/irods_7220] do not redefine `log`

---

CMakeLists.txt
core/CMakeLists.txt
endpoints/authentication/CMakeLists.txt
endpoints/collections/CMakeLists.txt
endpoints/data_objects/CMakeLists.txt
endpoints/information/CMakeLists.txt
endpoints/query/CMakeLists.txt
endpoints/resources/CMakeLists.txt
endpoints/rules/CMakeLists.txt
endpoints/shared/CMakeLists.txt
endpoints/tickets/CMakeLists.txt
endpoints/users_groups/CMakeLists.txt
endpoints/zones/CMakeLists.txt

In service of irods/irods#6251
In service of irods/irods#6256
Once this is merged, a 4-3-stable branch should be created.

[irods/irods#6251,irods/irods#6256] find_package for fmt and spdlog

---

CMakeLists.txt

In service of irods/irods#7265

[irods/irods#7265] Add missing `CMAKE_EXE_LINKER_FLAGS_RELEASE_INIT` (main)

---

CMakeLists.txt

In service of irods/irods#7265

[irods/irods#7265] Add missing `CMAKE_EXE_LINKER_FLAGS_RELEASE_INIT` (4-3-stable)

---

API.md
README.md
core/include/irods/private/http_api/common.hpp
core/src/common.cpp
core/src/main.cpp
endpoints/authentication/src/main.cpp
test/config.py
test/test_auth_endpoint.py

The primary goal of this PR is to allow the HTTP API to receive access tokens on all of the iRODS HTTP API endpoints. We do this while moving away from the currently used HTTP API tokens in OAuth related authorization. A major reason for moving towards OAuth tokens is for better integration with existing providers, as well as improved compliance to desired token properties (e.g. token expiration, revocation).
As part of this implementation, confidential clients and user mapping needed to be implemented. The implementation of confidential clients should allow for the HTTP API to contact the OpenID Provider's introspection endpoint, among other benefits. Additionally, the alternate user mapping system allows for further flexibility on how to map tokens to iRODS users.
---
This allows access …

[#155,#235,#108] Make HTTP API a Protected Resource, Add support of Confidential Client, User Mapping

---

API.md

The zone operation in question is disabled until we fully understand the iRODS API. Once we have a grasp on the API, we can revert this commit.

[#290] Remove API documentation for disabled zone operation

---

API.md
CMakeLists.txt
README.md
build_packages.sh
core/CMakeLists.txt
endpoints/authentication/CMakeLists.txt
endpoints/collections/CMakeLists.txt
endpoints/data_objects/CMakeLists.txt
endpoints/information/CMakeLists.txt
endpoints/information/src/main.cpp
endpoints/query/CMakeLists.txt
endpoints/query/src/main.cpp
endpoints/resources/CMakeLists.txt
endpoints/rules/CMakeLists.txt
endpoints/shared/CMakeLists.txt
endpoints/tickets/CMakeLists.txt
endpoints/users_groups/CMakeLists.txt
endpoints/zones/CMakeLists.txt
irods_builder.Dockerfile
irods_runner.Dockerfile
test/config.py

All tests pass _(excluding OIDC tests)_.
Docker-related changes work as well.

[#272] Update dependencies to iRODS 4.3.2 for GenQuery2

---

core/include/irods/private/http_api/log.hpp
core/src/multipart_form_data.cpp
core/src/session.cpp
endpoints/authentication/src/main.cpp
endpoints/collections/src/main.cpp
endpoints/data_objects/src/main.cpp
endpoints/information/src/main.cpp
endpoints/query/src/main.cpp
endpoints/resources/src/main.cpp
endpoints/rules/src/main.cpp
endpoints/shared/src/shared_api_operations.cpp
endpoints/tickets/src/main.cpp
endpoints/users_groups/src/main.cpp
endpoints/zones/src/main.cpp

This PR results in many log messages reporting the IP address like so:
```
[2024-08-21 09:38:18.634] [P:1374617] [debug] [T:1374660] [127.0.0.1] on_read: Header: (User-Agent, python-requests/2.31.0)
[2024-08-21 09:38:18.634] [P:1374617] [debug] [T:1374660] [127.0.0.1] on_read: Header: (Accept-Encoding, gzip, deflate)
[2024-08-21 09:38:18.635] [P:1374617] [debug] [T:1374660] [127.0.0.1] on_read: Header: (Accept, */*)
[2024-08-21 09:38:18.635] [P:1374617] [debug] [T:1374660] [127.0.0.1] on_read: Header: (Connection, keep-alive)
[2024-08-21 09:38:18.635] [P:1374617] [debug] [T:1374660] [127.0.0.1] on_read: Header: (Authorization, Bearer e2887051-ea00-41cb-91c1-0fb6aebca57a)
[2024-08-21 09:38:18.635] [P:1374617] [debug] [T:1374660] [127.0.0.1] on_read: Header: (Content-Length, 25)
[2024-08-21 …
```

[#73] Log IP address of incoming client request

---

README.md
core/src/main.cpp
endpoints/data_objects/src/main.cpp
test/test_irods_http_api.py

All tests pass.
Considering the idea of passing an input struct rather than 10+ parameters. Not required, but much easier to deal with from a code standpoint and while reading. Can also handle this later.
TODO: Add tests which force the use of bg thread pool when writing to iRODS. The number of writes depend on the configuration of the HTTP API, so we'll need to document the assumptions of the test suite too.

[#196] Implement incremental write loop for write operation

---

core/src/main.cpp

This change causes the server to terminate and print a message to the terminal when the socket is already bound by another instance. Admins can expect to see the following when this occurs.
```
Validating configuration file ...                                                                                                                                    
No JSON schema file provided. Using default.                                                                                                                         
Configuration passed validation!                                                                                                                                     
[2024-09-25 15:18:56.118] [P:581459] [info] [T:581459] Initializing server. …
```

[#335] Avoid infinite loop when listening socket is already bound

---

API.md
CMakeLists.txt
README.md
core/include/irods/private/http_api/globals.hpp
core/src/common.cpp
core/src/globals.cpp
core/src/main.cpp
plugins/CMakeLists.txt
plugins/user_mapping/CMakeLists.txt
plugins/user_mapping/include/irods/http_api/plugins/user_mapping/interface.h
plugins/user_mapping/src/local_file.cpp
plugins/user_mapping/src/user_claim.cpp

This PR would move various implementations of user mapping to a separate shared library, allowing for user-defined plugins to be developed against the plugin interface.
A default 'local file' plugin would ship with the HTTP API, with behavior similar to `user_attribute_mapping`. The two changes would be that the mapping definition would live in a separate file, and be the file would be reread for changes. This would allow for the mapping to be updated without restarting the HTTP API.

[#293] Make user mapping defined by plugin

---

endpoints/authentication/src/main.cpp

Compiles.
@MartinFlores751 Please verify this PR results in the user receiving a 401 when the mapped iRODS username does not exist in the catalog.

[#338] OIDC: Confirm mapped iRODS username exists before returning token

---

core/src/main.cpp
test/config.py

- Schema files/info does not need to include version info
- Config file for testing does not need to include version info

[#269] Collapse version information to single point of control

---

README.md

Make clear the use of `tls_certificates_directory`.

[#243] Further document `tls_certificates_directory`

---

core/src/main.cpp

```
$ irods_http_api config.json 
Validating configuration file ...
No JSON schema file provided. Using default.
Configuration passed validation!
[2024-11-05 18:54:10.724] [P:15090] [info] [T:15090] Initializing server.
[2024-11-05 18:54:10.724] [P:15090] [trace] [T:15090] Verifying OIDC endpoint configuration
[2024-11-05 18:54:10.724] [P:15090] [trace] [T:15090] Unable to establish connection to OpenID Provider. Reason: [connect: Connection refused [system:111 at /opt/irods-externals/boost-libcxx1.81.0-1/include/boost/asio/detail/reactive_socket_service.hpp:587:33 in function 'connect']]
[2024-11-05 18:54:10.724] [P:15090] [error] [T:15090] Invalid OIDC configuration, server not starting.
```

[#244] Provide clear message on OpenID connection error

---

endpoints/authentication/src/main.cpp

This change is safe as it just reduces the number writable bytes to the destination buffer by 1 as defined by the `CheckAuthCredentialsInput` input struct.
See https://docs.irods.org/4.3.3/doxygen/structCheckAuthCredentialsInput.html.

[#365] Leave space in buffer for null-terminating byte when using `std::string::copy`

---

.github/workflows/build-irods-http-api-ubuntu.yml
core/CMakeLists.txt

Ccache can be removed if we want a clean build every run.

[#382] Add build action for PRs

---

endpoints/data_objects/src/main.cpp

Found using ASAN, logs follow:
```
=================================================================
==7599==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 320 byte(s) in 4 object(s) allocated from:
#0 0x763a3f in __interceptor_realloc /externals/clang13.0.1-0_src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:148:3
#1 0x7dbb2affc056 in addKeyVal (/lib/libirods_common.so.4.3.2+0x174056)
#2 0xc6c323 in decltype(static_cast<(anonymous namespace)::op_register(std::__1::shared_ptr<irods::http::session>, boost::beast::http::message<true, boost::beast::http::basic_string_body<char, std::__1::char_traits<char>, std::__1::allocator<char> >, boost::beast::http::basic_fields<std::__1::allocator<char> > >&, std::__1::unordered_map<std::__1::basic_string<char, …
```

[#389] Fix KeyVal memory leak

---

README.md
core/src/main.cpp
core/src/openid.cpp

This has the changes made from #376, with the suggestions of that PR applied in this PR.

[#375] Add optional strict check to `aud` member of introspection endpoint response

---

CMakeLists.txt
core/src/main.cpp
ub-sanitizer-ignorelist.txt

[#390] Add UBSAN

---

core/src/main.cpp

This prevents a past the end iterator dereference.

[#391] Add missing return to `set_log_level(...)`

---

test/README.md
test/keycloak/README.md
test/keycloak/example-realm-export.json
test/keycloak/irods-http-api-keycloak.Dockerfile

The environment should start the same on every standup by using the realm export. Asymmetric keys are only good for 10 years, I think. Remember to update before then!

[#242] Create custom keycloak image for testing

---

core/src/main.cpp
core/src/openid.cpp

Issue quick link: #412
This PR attempts to fix hangs in disconnecting that block until some timeout is reached. The problem is that, by default, HTTP 1.1 assumes that connections will be kept alive. We add `.keep_alive(false)` to the request to close the connection.
~This PR is in draft, since the specifics of the issue are not completely clear yet.~

[#412] Ensure outbound HTTP communications terminate correctly (main)

---

README.md
core/src/openid.cpp

Issue quick link: #419
Remove the default of using `client_secret` for a JWT that is signed with a symmetric key.

[#419] Remove non-standard behavior for symmetrically signed JWTs

---

README.md
core/CMakeLists.txt
core/include/irods/private/http_api/compatibility.hpp
core/src/compatibility.cpp
core/src/main.cpp
endpoints/data_objects/src/main.cpp
endpoints/users_groups/src/main.cpp
irods_builder.el8.Dockerfile
irods_builder.el9.Dockerfile
irods_builder.ub22.Dockerfile
test/test_irods_http_api.py

Confirmed the non-OIDC tests pass for the following configurations:
- HTTP API compiled against iRODS 5.0.1
- Connected to iRODS 5.0.1 server
- Connected to iRODS 4.3.4 server
- Connected to iRODS 4.3.3 server
- HTTP API compiled against iRODS 4.3.2
- Connected to iRODS 5.0.1 server
- Connected to iRODS 4.3.4 server
- Connected to iRODS 4.3.3 server

Fix iRODS compatibility / Fix test failures / Documentation (main)

---

API.md
endpoints/data_objects/src/main.cpp
test/test_irods_http_api.py

All non-OIDC tests pass.
A HTTP status code of 400 (Bad Request) is returned to the client if the atime is specified in the request and the HTTP API is connected to an iRODS server earlier than 5.0.0. This decision guarantees the client will have a consistent experience around the use of the atime property.
This PR does make it more difficult to test 4.3 servers due to the atime property being used in a test. #440 will help with fixing that issue.

[#431] Add support for modifying the atime of a replica

---

README.md
plugins/user_mapping/src/user_claim.cpp

Issue quick link: #421
This PR attempts to address the issue of irregular user claims being returned by some OpenID providers by allowing for a configuration specifying a regex to match and then format the results.
---
I'll finish the following before taking the PR out of draft:
- This would disable the regex feature if both are missing and fail if one is missing

[#421] Allow for a regex to modify the user claim from an OpenID Provider (main)

---

README.md
core/src/common.cpp
core/src/main.cpp

Issue quick link: #448
This PR introduces a new schema item to select the desired access token validation method. The selected method will be the only method that runs until the configuration is changed and the server is restarted.
If you have suggestions for the schema item name and names for the enums, they would be appreciated.
---
Before getting out of draft:

[#448] Make access token validation method selectable (main)

---

API.md
endpoints/data_objects/src/main.cpp
test/test_irods_http_api.py

Will run the non-OIDC tests today.
As mentioned in #454, the checks for incompatible parameters are disabled. The HTTP API has operations which do these kinds of checks, but I'm leaning towards it shouldn't since that duplicates the work of the iRODS server. One can argue that detecting such situations is good because it protects the iRODS server from needing to do it. One of the goals of the HTTP API is to make interacting with iRODS easier, that means having guard rails around operations.
So yeah, still need to think through if the checks are worth restoring or removing.

[#271] Implement truncate operation for /data-objects endpoint (main)
